# Site settings
author: Tom White
title: From the Small Screen to the Even Smaller Screen
header-img: img/home-bg.png
email: eugene.white@gmail.com
copyright_name: Tom White
description: > # this means to ignore newlines until "baseurl:"
  A television actor learns to code
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  tomciv9000

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
